=== Goncalo-Marques/ecomap/web/src/locales/schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"properties": {
		"clear": {
			"type": "string"
		},
		"pagination.of": {
			"type": "string"
		},
		"createdAt": {
			"type": "string"
		},
		"modifiedAt": {
			"type": "string"
		},
		"generalInfo": {
			"type": "string"
		},
		"additionalInfo": {
			"type": "string"
		},
		"containers.title": {
			"type": "string"
		},
		"containers.notFound.title": {
			"type": "string"
		},
		"containers.notFound.description": {
			"type": "string"
		},
		"containers.search": {
			"type": "string"
		},
		"containers.category": {
			"type": "string"
		},
		"containers.location": {
			"type": "string"
		},
		"containers.location.unknownWay": {
			"type": "string"
		},
		"containers.category.general": {
			"type": "string"
		},
		"containers.category.paper": {
			"type": "string"
		},
		"containers.category.plastic": {
			"type": "string"
		},
		"containers.category.metal": {
			"type": "string"
		},
		"containers.category.glass": {
			"type": "string"
		},
		"containers.category.organic": {
			"type": "string"
		},
		"containers.category.hazardous": {
			"type": "string"
		},
		"error.requiredField": {
			"type": "string"
		},
		"error.unexpected": {
			"type": "string"
		},
		"signin.title": {
			"type": "string"
		},
		"signin.username.label": {
			"type": "string"
		},
		"signin.username.placeholder": {
			"type": "string"
		},
		"signin.password.label": {
			"type": "string"
		},
		"signin.password.placeholder": {
			"type": "string"
		},
		"signin.button": {
			"type": "string"
		},
		"signin.error.incorrectCredentials": {
			"type": "string"
		},
		"sidebar.dashboard": {
			"type": "string"
		},
		"sidebar.map": {
			"type": "string"
		},
		"sidebar.routes": {
			"type": "string"
		},
		"sidebar.containers": {
			"type": "string"
		},
		"sidebar.warehouses": {
			"type": "string"
		},
		"sidebar.trucks": {
			"type": "string"
		},
		"sidebar.reports": {
			"type": "string"
		},
		"sidebar.employees": {
			"type": "string"
		},
		"notFound.title": {
			"type": "string"
		},
		"notFound.description": {
			"type": "string"
		},
		"forbidden.title": {
			"type": "string"
		},
		"forbidden.description": {
			"type": "string"
		},
		"map.layers": {
			"type": "string"
		},
		"employees.title": {
			"type": "string"
		},
		"employees.addEmployee": {
			"type": "string"
		},
		"employees.search": {
			"type": "string"
		},
		"employees.save": {
			"type": "string"
		},
		"employees.cancel": {
			"type": "string"
		},
		"employees.personalInfo": {
			"type": "string"
		},
		"employees.firstName": {
			"type": "string"
		},
		"employees.lastName": {
			"type": "string"
		},
		"employees.username": {
			"type": "string"
		},
		"employees.birthdate": {
			"type": "string"
		},
		"employees.phoneNumber": {
			"type": "string"
		},
		"employees.location": {
			"type": "string"
		},
		"employees.work": {
			"type": "string"
		},
		"employees.startTime": {
			"type": "string"
		},
		"employees.position": {
			"type": "string"
		},
		"employees.endTime": {
			"type": "string"
		},
		"employees.select.location": {
			"type": "string"
		},
		"employees.name": {
			"type": "string"
		},
		"employees.schedule": {
			"type": "string"
		},
		"employees.role": {
			"type": "string"
		},
		"employees.role.manager": {
			"type": "string"
		},
		"employees.role.wasteOperator": {
			"type": "string"
		}
	}
}

=== Goncalo-Marques/ecomap/web/src/locales/pt.json
{
	"$schema": "./schema.json",
	"signin.title": "Iniciar sessão",
	"signin.username.label": "Utilizador",
	"signin.username.placeholder": "Digite o seu nome de utilizador",
	"signin.password.label": "Password",
	"signin.password.placeholder": "Digite a sua password",
	"signin.button": "Iniciar sessão"
}

=== Goncalo-Marques/ecomap/web/src/locales/en.json
{
	"$schema": "./schema.json",
	"error.requiredField": "Required field",
	"error.unexpected": "An unexpected error occurred. Please try again later or contact the support team.",
	"signin.title": "Sign in",
	"signin.username.label": "Username",
	"signin.username.placeholder": "Enter your username",
	"signin.password.label": "Password",
	"signin.password.placeholder": "Enter your password",
	"signin.button": "Sign in",
	"signin.error.incorrectCredentials": "Invalid credentials. Either the username or password are incorrect.",
	"sidebar.dashboard": "Dashboard",
	"sidebar.map": "Map",
	"sidebar.routes": "Routes",
	"sidebar.containers": "Containers",
	"sidebar.warehouses": "Warehouses",
	"sidebar.trucks": "Trucks",
	"sidebar.reports": "Reports",
	"sidebar.employees": "Employees",
	"notFound.title": "Page not found",
	"notFound.description": "The page you are looking for does not exist.",
	"forbidden.title": "Access forbidden",
	"forbidden.description": "You do not have permission to access this page.",
	"map.layers": "Layers",
	"employees.title": "Employees",
	"employees.addEmployee": "Add new employee",
	"employees.search": "Search by name",
	"employees.save": "Save",
	"employees.cancel": "Cancel",
	"employees.personalInfo": "Personal information",
	"employees.firstName": "First Name",
	"employees.lastName": "Last Name",
	"employees.username": "Username",
	"employees.birthdate": "Birthdate",
	"employees.location": "Location",
	"employees.phoneNumber": "Phone Number",
	"employees.work": "Work",
	"employees.startTime": "Start time",
	"employees.endTime": "End time",
	"employees.position": "Position",
	"employees.select.location": "Select Location"
}
